### PR TITLE
#158934020 Serving UI Templates to Github Pages 

### PR DESCRIPTION
**Pull request by SrMoffat**
### What does the PR do?
Updates the repo with UI templates to be hosted on github pages using `gh-pages` branch

### Description of tasks completed
1.	Signup page
2.	Login page
3.	Add journal entry page
4.	View journal entry details page
5.	View all journal entries
6.	Modify a journal entry page
7.	Set reminder page
8.	Get reminder page

### Manual Testing 
Proceed to [github pages][https://github.com/srmoffat/MyDiary/UI/index.html] and have a feel of the UI/UX. ```To access the dashboard just press the sign in button.```

### Screenshots
signup
signin
dashboard
addentry
viewentries
entrydetails
setreminder
notifications

### CODE REVIEW

**Comment by YA7YA-H** [comment]
wow nice Excellent

**Comment by YA7YA-H** [comment]
You done with it ...

**Comment by YA7YA-H** [comment]
Now create gh-pages :1st_place_medal: 
hope ni responsive

**Comment by imireallan** [comment]
safi sana..looks like a complete product..good work

**Pull request merged**
